language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-29.0.2
    - android-28
licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
   - google-gdk-license-.+
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
script:
  - ./gradlew build connectedCheck
